"""extend_settings_table

Revision ID: 20241209_extend_settings_table
Revises: e4b7e8c165c1
Create Date: 2024-12-09 11:45:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20241209_extend_settings_table"
down_revision: Union[str, None] = "e4b7e8c165c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('timezone', sa.String(), server_default='Europe/Moscow', nullable=False))
    op.add_column('settings', sa.Column('date_format', sa.String(), server_default='DD.MM.YYYY', nullable=False))
    op.add_column('settings', sa.Column('time_format', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('settings', sa.Column('prayer_notifications_on', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('settings', sa.Column('event_notifications_on', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('settings', sa.Column('data_export_requested', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('settings', sa.Column('account_deletion_requested', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('settings', sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.add_column('settings', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'updated_at')
    op.drop_column('settings', 'created_at')
    op.drop_column('settings', 'account_deletion_requested')
    op.drop_column('settings', 'data_export_requested')
    op.drop_column('settings', 'event_notifications_on')
    op.drop_column('settings', 'prayer_notifications_on')
    op.drop_column('settings', 'time_format')
    op.drop_column('settings', 'date_format')
    op.drop_column('settings', 'timezone')
    # ### end Alembic commands ###
