"""add education stream certificate models

Revision ID: fd4573ae895b
Revises: df21e0099e90
Create Date: 2025-12-11 14:15:31.266802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd4573ae895b'
down_revision: Union[str, None] = 'df21e0099e90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем поле is_completed в user_course_progress
    op.add_column('user_course_progress', sa.Column('is_completed', sa.Boolean(), nullable=False, server_default='false'))
    
    # Добавляем поля has_test и test_id в course_modules
    op.add_column('course_modules', sa.Column('has_test', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('course_modules', sa.Column('test_id', sa.Integer(), nullable=True))
    op.create_foreign_key('course_modules_test_id_fkey', 'course_modules', 'tests', ['test_id'], ['id'])
    
    # Добавляем поле module_id в tests
    op.add_column('tests', sa.Column('module_id', sa.Integer(), nullable=True))
    op.create_foreign_key('tests_module_id_fkey', 'tests', 'course_modules', ['module_id'], ['id'])
    
    # Создаем таблицу streams
    op.create_table('streams',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('speaker', sa.String(length=100), nullable=True),
        sa.Column('scheduled_time', sa.DateTime(), nullable=False),
        sa.Column('duration_minutes', sa.Integer(), nullable=False, server_default='60'),
        sa.Column('stream_url', sa.String(length=500), nullable=True),
        sa.Column('recording_url', sa.String(length=500), nullable=True),
        sa.Column('is_upcoming', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('max_participants', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.PrimaryKeyConstraint('id', name='streams_pkey')
    )
    
    # Создаем таблицу stream_reminders
    op.create_table('stream_reminders',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('stream_id', sa.Integer(), nullable=False),
        sa.Column('reminded_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], name='stream_reminders_stream_id_fkey'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='stream_reminders_user_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='stream_reminders_pkey'),
        sa.UniqueConstraint('user_id', 'stream_id', name='uq_user_stream_reminder')
    )
    
    # Создаем таблицу certificates
    op.create_table('certificates',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('course_id', sa.Integer(), nullable=False),
        sa.Column('certificate_url', sa.String(length=500), nullable=False),
        sa.Column('issued_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.Column('score', sa.Float(), nullable=False, server_default='0.0'),
        sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='certificates_course_id_fkey'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='certificates_user_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='certificates_pkey'),
        sa.UniqueConstraint('user_id', 'course_id', name='uq_user_course_certificate')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificates')
    op.drop_table('stream_reminders')
    op.drop_table('streams')
    op.drop_constraint('tests_module_id_fkey', 'tests', type_='foreignkey')
    op.drop_column('tests', 'module_id')
    op.drop_constraint('course_modules_test_id_fkey', 'course_modules', type_='foreignkey')
    op.drop_column('course_modules', 'test_id')
    op.drop_column('course_modules', 'has_test')
    op.drop_column('user_course_progress', 'is_completed')
    # ### end Alembic commands ###
