"""add education tables

Revision ID: df21e0099e90
Revises: f53f56289e57
Create Date: 2025-12-11 11:04:36.031181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df21e0099e90'
down_revision: Union[str, None] = 'f53f56289e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('community_events', 'event_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('LECTURE', 'MEETING', 'COURSE', 'OTHER', name='eventtype', native_enum=False),
               existing_nullable=False)
    op.alter_column('community_events', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ACTIVE', 'CANCELLED', 'FINISHED', name='eventstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('event_proposals', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='proposalstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('event_registrations', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('CONFIRMED', 'CANCELLED', 'WAITING', name='registrationstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('settings', 'notification_on',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_unique_constraint(None, 'settings', ['user_id'])
    op.alter_column('users', 'streak_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'streak_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'settings', type_='unique')
    op.alter_column('settings', 'notification_on',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('event_registrations', 'status',
               existing_type=sa.Enum('CONFIRMED', 'CANCELLED', 'WAITING', name='registrationstatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('event_proposals', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='proposalstatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('community_events', 'status',
               existing_type=sa.Enum('ACTIVE', 'CANCELLED', 'FINISHED', name='eventstatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('community_events', 'event_type',
               existing_type=sa.Enum('LECTURE', 'MEETING', 'COURSE', 'OTHER', name='eventtype', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
