"""add_events_calendar_tables_simple

Revision ID: 84d148710529
Revises: add_prayer_notification_fields
Create Date: 2025-12-10 22:34:19.736722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84d148710529'
down_revision: Union[str, None] = 'add_prayer_notification_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create community_events table with VARCHAR for enums
    op.create_table('community_events',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('start_time', sa.DateTime(), nullable=False),
        sa.Column('location', sa.String(length=200), nullable=True),
        sa.Column('event_type', sa.String(length=20), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('max_participants', sa.Integer(), nullable=True),
        sa.Column('created_by', sa.BigInteger(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Add CHECK constraints for event_type
    op.execute("""
        ALTER TABLE community_events 
        ADD CONSTRAINT community_events_event_type_check 
        CHECK (event_type IN ('lecture', 'meeting', 'course', 'other'))
    """)
    
    # Add CHECK constraints for status
    op.execute("""
        ALTER TABLE community_events 
        ADD CONSTRAINT community_events_status_check 
        CHECK (status IN ('active', 'cancelled', 'finished'))
    """)
    
    # Create event_registrations table
    op.create_table('event_registrations',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('event_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('registered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('cancelled_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['event_id'], ['community_events.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'event_id', name='uq_user_event')
    )
    
    # Add CHECK constraints for registration status
    op.execute("""
        ALTER TABLE event_registrations 
        ADD CONSTRAINT event_registrations_status_check 
        CHECK (status IN ('confirmed', 'cancelled', 'waiting'))
    """)
    
    # Create event_proposals table
    op.create_table('event_proposals',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('suggested_date', sa.DateTime(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('admin_notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('reviewed_at', sa.DateTime(), nullable=True),
        sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Add CHECK constraints for proposal status
    op.execute("""
        ALTER TABLE event_proposals 
        ADD CONSTRAINT event_proposals_status_check 
        CHECK (status IN ('pending', 'approved', 'rejected'))
    """)
    
    # Add new columns to settings table
    op.add_column('settings', sa.Column('notify_1day_before', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('settings', sa.Column('notify_on_day', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('settings', sa.Column('notify_juma', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('settings', sa.Column('notify_event_reminder', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('settings', sa.Column('notify_event_changes', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove columns from settings
    op.drop_column('settings', 'notify_event_changes')
    op.drop_column('settings', 'notify_event_reminder')
    op.drop_column('settings', 'notify_juma')
    op.drop_column('settings', 'notify_on_day')
    op.drop_column('settings', 'notify_1day_before')
    
    # Drop tables
    op.drop_table('event_proposals')
    op.drop_table('event_registrations')
    op.drop_table('community_events')
    # ### end Alembic commands ###
